In [1]:
import pandas as pd 
import numpy as np 
from bs4 import BeautifulSoup
from requests import get

In [18]:
def get_resp(base_url1, player_name,base_url2):
    url = base_url1+player+base_url2
    response = get(url)
    print(response.status_code)
    return(response)

def parser(response, cols):
    nfl = BeautifulSoup(response.content, 'html.parser')
    table = nfl.find(lambda tag: tag.name=='table') 
    rows = table.find_all('tr')
    df = pd.DataFrame(columns = cols)
    
    for i in range(1, len(rows)):
        print(i)
        a = rows[i].get_text()
        b = a.replace('\n', ',')
        b = b.strip()
        b = b.replace(' ','')
        c = b[1:].split(',')
        d = []
        for j in range(0, len(c)): 
            if c[j]!='': 
                d.append(c[j])
        for j in range(0,len(cols)):

            try:
                #print(d[j])
                df.loc[i-1, cols[j]] = d[j]
            except: 
                df.loc[i-1, cols[j]] = ''
            
            
    return(df)

def get_def_stats(url, cols):
    tables = pd.read_html(url)
    df = tables[1]
    df.columns = cols
    #df.columns = ['Week','Day', 'Date','Time','Link','W/L','OT','Rec','H/A','Opp','TM','Opp Score','Offense 1st','Off tot yd', 'off pass yds',
             #'Off rush Yards', 'Off TO', 'Def 1st D', 'Def Tot Yd','Deff Pass Yd', 'Def Rush Yards', 'Def TO','Ex Off','Exp Def','Ex Sp. Tms' ]
    
    return(df)

def get_rb_stats(url, cols): 
    tables = pd.read_html(url)
    df = tables[0]
    df.columns= cols
    return(df)

In [19]:
cols = ['Wk', 'Date', 'Opp', 'Res','Att','Yds','Avg','Lng','Td','Rec','Yds1','Avg1','Lng1','Td1','Fum','Lost']
base1 = 'https://www.nfl.com/players/'
player = 'aaron-jones'
base2 = '/stats/logs/'


rb = get_rb_stats(r'https://www.nfl.com/players/aaron-jones/stats/logs/', cols)
rb

,Wk,Date,Opp,Res,Att,Yds,Avg,Lng,Td,Rec,Yds1,Avg1,Lng1,Td1,Fum,Lost
0,11,11/22/2020,@Colts,L 31 - 34,10.0,41.0,4.1,15.0,1.0,4.0,30.0,7.5,14.0,0.0,NaN,NaN
1,10,11/15/2020,Jaguars,W 24 - 20,13.0,46.0,3.5,20.0,0.0,5.0,49.0,9.8,14.0,0.0,1.0,0.0
2,9,11/06/2020,@49ers,W 34 - 17,15.0,58.0,3.9,11.0,0.0,5.0,21.0,4.2,15.0,0.0,NaN,NaN
3,8,11/01/2020,Vikings,L 22 - 28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,3,09/28/2020,@Saints,W 37 - 30,16.0,69.0,4.3,19.0,1.0,2.0,17.0,8.5,12.0,0.0,NaN,NaN
5,7,10/25/2020,@Texans,W 35 - 20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,2,09/20/2020,Lions,W 42 - 21,18.0,168.0,9.3,75.0,2.0,4.0,68.0,17.0,30.0,1.0,NaN,NaN
7,6,10/18/2020,@Buccaneers,L 10 - 38,10.0,15.0,1.5,7.0,1.0,3.0,26.0,8.7,20.0,0.0,NaN,NaN
8,4,10/06/2020,Falcons,W 30 - 16,15.0,71.0,4.7,23.0,0.0,5.0,40.0,8.0,23.0,1.0,NaN,NaN
9,1,09/13/2020,@Vikings,W 43 - 34,16.0,66.0,4.1,15.0,1.0,4.0,10.0,2.5,6.0,0.0,1.0,0.0

In [23]:
cols_to_numeric = ['Wk','Att','Yds','Avg','Lng','Td','Rec','Yds1','Avg1','Lng1','Td1','Fum','Lost']

play_stats= rb
for i in range(0, len(cols_to_numeric)): 
    #print(i)
    col = cols_to_numeric[i]
    #print(col)
    play_stats[col] = pd.to_numeric(play_stats[col])
    
play_stats

,Wk,Date,Opp,Res,Att,Yds,Avg,Lng,Td,Rec,Yds1,Avg1,Lng1,Td1,Fum,Lost
0,11,11/22/2020,@Colts,L 31 - 34,10.0,41.0,4.1,15.0,1.0,4.0,30.0,7.5,14.0,0.0,NaN,NaN
1,10,11/15/2020,Jaguars,W 24 - 20,13.0,46.0,3.5,20.0,0.0,5.0,49.0,9.8,14.0,0.0,1.0,0.0
2,9,11/06/2020,@49ers,W 34 - 17,15.0,58.0,3.9,11.0,0.0,5.0,21.0,4.2,15.0,0.0,NaN,NaN
3,8,11/01/2020,Vikings,L 22 - 28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,3,09/28/2020,@Saints,W 37 - 30,16.0,69.0,4.3,19.0,1.0,2.0,17.0,8.5,12.0,0.0,NaN,NaN
5,7,10/25/2020,@Texans,W 35 - 20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,2,09/20/2020,Lions,W 42 - 21,18.0,168.0,9.3,75.0,2.0,4.0,68.0,17.0,30.0,1.0,NaN,NaN
7,6,10/18/2020,@Buccaneers,L 10 - 38,10.0,15.0,1.5,7.0,1.0,3.0,26.0,8.7,20.0,0.0,NaN,NaN
8,4,10/06/2020,Falcons,W 30 - 16,15.0,71.0,4.7,23.0,0.0,5.0,40.0,8.0,23.0,1.0,NaN,NaN
9,1,09/13/2020,@Vikings,W 43 - 34,16.0,66.0,4.1,15.0,1.0,4.0,10.0,2.5,6.0,0.0,1.0,0.0

In [21]:
play_stats['Yds']

  Yds Yds
0   4   4
1   5   5
2   5   5
3
4   2   2
5
6   4   4
7   3   3
8   5   5
9   4   4

In [ ]:
play_stats.sort_values(by = 'Wk', inplace = True)
play_stats.reset_index(inplace = True, drop = True)
play_stats

In [ ]:
play_stats.dtypes

In [ ]:


def_df = get_def_stats(r'https://www.pro-football-reference.com/teams/mia/2020.htm', ['Week','Day', 'Date','Time','Link','W/L','OT','Rec','H/A','Opp','TM','Opp Score','Offense 1st','Off tot yd', 'off pass yds',
             'Off rush Yards', 'Off TO', 'Def 1st D', 'Def Tot Yd','Deff Pass Yd', 'Def Rush Yards', 'Def TO','Ex Off','Exp Def','Ex Sp. Tms' ])
def_df

In [ ]:
def_df.columns.tolist()

In [ ]:
cols_to_keep = ['Week','Opp Score','Opp','Def Tot Yd','Deff Pass Yd','Def Rush Yards','Def TO']
df3 = def_df[cols_to_keep]
df3

In [ ]:
cols_to_numeric = ['Week','Opp Score','Def Tot Yd','Deff Pass Yd','Def Rush Yards','Def TO']

for i in range(0, len(cols_to_numeric)): 
    col = cols_to_numeric[i]
    df3[col] = pd.to_numeric(df3[col])

df3.dtypes

In [ ]:
df3.sort_values(by = 'Week')
df3.reset_index(inplace = True, drop = True)
df3

In [ ]:
#'Def Passing Yards Avg','Def Running Yards Avg','Turnovers Avg'
df3.dropna(inplace = True)
df3['Def Passing Yards Avg'] = df3['Deff Pass Yd'].rolling(5).mean()
df3['Def Running Yards Avg'] = df3['Def Rush Yards'].rolling(5).mean()
df3['Turnovers Avg'] = df3['Def TO'].rolling(5).mean()
df3

In [ ]:
play_stats
play_stats.fillna(0, inplace = True)
play_stats

In [ ]:
x_cols = ['passing_att','passing_ints_pts', 'passing_tds_pts', 'passing_twoptm_pts', 'passing_yds_pts', 
          'rushing_td_pts','rushing_yds_pts','fumbles_lost_pts','Def Passing Yards Avg',
          'Def Running Yards Avg','Turnovers Avg']

week = 10 

df_for_regression = pd.DataFrame()
df_for_regression['Week'] = play_stats['Wk']
df_for_regression['passing_att'] = play_stats['Att']
df_for_regression['passing_ints_pts'] = play_stats['Int'] * -1 
df_for_regression['passing_tds_pts'] = play_stats['TD']*4
#df_for_regression['passing_twoptm_pts'] = play_stats['']
df_for_regression['passing_yds_pts'] = play_stats['Yds']*0.04
df_for_regression['rushing_td_pts'] = play_stats['Td1'] * 6
df_for_regression['fumbles_lost_pts'] = play_stats['Fum'] * -1
df_for_regression['rushing_yds_pts'] = play_stats['Yds1'] * 0.1 
df_for_regression

In [ ]:
week_for_off = 10 

x_cols = ['passing_att','passing_ints_pts', 'passing_tds_pts', 'passing_yds_pts', 
          'rushing_td_pts','rushing_yds_pts','fumbles_lost_pts','Def Passing Yards Avg',
          'Def Running Yards Avg','Turnovers Avg']

coefs = [-2.3006,-2.5185,1.07,5.2943,-2.3527,-1.4089,0.1970,-0.0354,-5.6371]
cols_player = df_for_regression.columns.tolist()[1:]
pts = 0
mask = df_for_regression['Week'] == week_for_off
df_for_calcs = df_for_regression[mask]
df_for_calcs
for i in range(0, len(cols_player)):
    pts = pts + df_for_calcs[x_cols[i]]*coefs[i]

week_for_def = 10 
mask = df3['Week'] == week_for_def
def_df_for_calcs = df3[mask]
def_cols = ['Def Passing Yards Avg','Def Running Yards Avg','Turnovers Avg']
for i in range(0, len(def_cols)): 
    pts = pts + coefs[i+6]*def_df_for_calcs[def_cols[i]]
pts

In [ ]:
df3

In [ ]:
6,7,8